#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.


#focaltech   
obj-$(CONFIG_FOCALTECH_FT6X06_UPDATA_FW)    	+= ft6x06_ex_fun.o
obj-$(CONFIG_FOCALTECH_FOCALTECH_USERDATA)	+= focaltech_ctl.o
obj-$(CONFIG_FOCALTECH_FT6X06_SYSDEBUG)  	+= ft6x06_sysdebug.o
obj-$(CONFIG_FOCALTECH_FT6X06_TS)    		+= ft6x06_ts.o

obj-$(CONFIG_FOCALTECH_FT6X06_SCAP_TEST) 	+= ini.o 
obj-$(CONFIG_FOCALTECH_FT6X06_SCAP_TEST)	+= scap_test_lib.o

